Repository utcs-scea/ava, pull requests merged in 2021-06, with the labels that each got.

#152 fix type convert warnings and constructor warnings
  cava/nightwatch/generator/c/buffer_handling.py
  cava/nightwatch/generator/c/callee.py
  cava/nightwatch/generator/c/caller.py
  cava/nightwatch/generator/c/guestlib.py
  cava/nightwatch/generator/c/printer.py
  cava/nightwatch/generator/c/replay.py
  cava/nightwatch/generator/c/stubs.py
  cava/nightwatch/generator/c/util.py
  cava/nightwatch/generator/c/worker.py
  cava/nightwatch/generator/common.py
  cava/nightwatch/main.py
  common/endpoint_lib.cpp
  common/endpoint_lib.hpp
Labels: refactor

#154 Resolve lint errors for CAvA
  cava/nightwatch/__init__.py
  cava/nightwatch/c_dsl.py
  cava/nightwatch/generator/__init__.py
  cava/nightwatch/generator/c/buffer_handling.py
  cava/nightwatch/generator/c/callee.py
  cava/nightwatch/generator/c/caller.py
  cava/nightwatch/generator/c/cmakelists.py
  cava/nightwatch/generator/c/command_handler.py
  cava/nightwatch/generator/c/guestlib.py
  cava/nightwatch/generator/c/instrumentation.py
  cava/nightwatch/generator/c/printer.py
  cava/nightwatch/generator/c/replay.py
  cava/nightwatch/generator/c/stubs.py
  cava/nightwatch/generator/c/util.py
  cava/nightwatch/generator/c/worker.py
  cava/nightwatch/generator/common.py
  cava/nightwatch/generator/header.py
  cava/nightwatch/generator/python/guestlib.py
  cava/nightwatch/indent.py
  cava/nightwatch/main.py
  cava/nightwatch/model.py
  cava/nightwatch/parser/__init__.py
  cava/nightwatch/parser/c/__init__.py
  cava/nightwatch/parser/c/clanginterface.py
  cava/nightwatch/parser/c/reload_libclang.py
  cava/nightwatch/parser/c/rules.py
  cava/nightwatch/parser/c/util.py
  cava/nightwatch/parser/python/__init__.py
  cava/nightwatch/parser/python/model_ext.py
Labels: refactor

#159 Enable format and lint checks for CAvA Python code
  .github/workflows/lint.yml
  scripts/check_python_format.sh
  scripts/check_python_lint.sh
Labels: enhancement, refactor

#167 Remove redefinition of global metadata_map
  common/endpoint_lib.cpp
  common/endpoint_lib.hpp
Labels: refactor

#171 Always generate C++ files for C and C++ specs
  .github/workflows/build_and_test.yml
  .github/workflows/build_and_test_cuda.yml
  cava/nightwatch/generator/c/cmakelists.py
  cava/nightwatch/generator/c/command_handler.py
  cava/nightwatch/generator/common.py
  cava/nightwatch/main.py
  cava/samples/test/libtrivial.c
Labels: enhancement

#162 Move batching enablement to Cava
  README.md
  cava/nightwatch/generator/c/callee.py
  cava/nightwatch/generator/c/caller.py
  cava/nightwatch/generator/c/cmakelists.py
  cava/nightwatch/generator/c/command_handler.py
  cava/nightwatch/generator/c/guestlib.py
  cava/nightwatch/generator/c/stubs.py
  cava/nightwatch/main.py
  cava/nightwatch/model.py
  cava/nightwatch/parser/c/nightwatch.h
  cava/nwcc
  cava/samples/onnxruntime/onnx_opt.cpp
  cava/samples/pytorch/pt_opt.cpp
  cava/samples/tensorflow/tf_opt.cpp
  docs/build_and_setup.md
  docs/generate_code.md
  generate.py
Labels: enhancement, refactor

#173 Use "/usr/bin/env python3" for generate.py script
  generate.py
Labels: bug

#175 Annotate more CUDA APIs to support PyTorch toy benchmark
  cava/headers/cudart_nw_internal.h
  cava/samples/pytorch/pt_dump.cpp
  cava/samples/pytorch/pt_opt.cpp
Labels: enhancement

#176 Fix a few PyTorch annotations
  cava/samples/pytorch/pt_opt.cpp
Labels: bug

#174 Add CUDA specification analyzer tool
  .gitignore
  tools/spec_analyzer/cuda_spec_analyzer.py
Labels: enhancement

#185 Disable pylint W1202 fstring interpolation in .flake8
  .flake8
Labels: refactor

#180 Annotate nvvm APIs in CUDART spec
  cava/samples/cudart/cudart.cpp
  generate.py
Labels: enhancement

#190 Check poll return value and loop in case of intr
  common/cmd_channel_socket_utilities.cpp
Labels: bug
